const assert = require('node:assert/strict');
const {render} = require('../assets/bilingual.js');
const {check, marked} = require('../scripts/check_bilingual.cjs');
const header = '# 杂志阅读 / Magazine reading\n\n- 原始链接：https://example.com\n\n---\n\n';
const body = '> **EN:** Five words stay together here.\n\n五个单词也属于完整的段落。\n\n> **EN:** This is the next paragraph of the same idea.\n\n这是同一论点的下一个段落。\n\n';
let result = render(header + body, marked);
assert.equal(result.sections.length,1);
assert.equal(result.sections[0].kind,'legacy');
assert(!result.sections[0].en.includes('<blockquote>'));
assert(result.sections[0].en.includes('Five words stay together here.'));
assert(result.sections[0].zh.includes('这是同一论点'));
result = render(header + body + '![图](image.png)\n\n' + body + '```txt\nEN: code stays\n```\n\n' + body, marked);
assert.equal(result.sections.length,3);
assert.equal((result.html.match(/<img /g)||[]).length,1);
assert(result.html.includes('EN: code stays'));
result = render(header + '> EN: Original paragraph.\n> ZH: 中文第一段。\n>\n> ZH: 中文第二段。', marked);
assert.equal(result.sections.length,1);
assert(result.sections[0].zh.includes('中文第二段'));
result = render(header + '- **EN: First item** with [a reference][ref]\n- **ZH: 第一条**说明\n- **EN: Second item**\n- **ZH: 第二条**说明\n\n[ref]: https://example.com/reference', marked);
assert.equal(result.sections.length,1);
assert(result.sections[0].en.includes('<strong>First item</strong>'));
assert(result.sections[0].en.includes('href="https://example.com/reference"'));
assert.equal((result.sections[0].en.match(/<li>/g)||[]).length,2);
const section = '<!-- bilingual:section -->\n\n<!-- lang:zh -->\n\n完整中文段落。\n\n> 真正的引语。\n\n<!-- lang:en -->\n\nComplete English prose.\n\n> A genuine quote.\n\n<!-- /bilingual:section -->';
result = render(header + section, marked);
assert.equal(result.sections.length,1);
assert.equal(result.sections[0].kind,'magazine-v1');
assert(result.sections[0].en.includes('<blockquote>'));
assert.deepEqual(check(header+section,{bilingual_format:'magazine-v1'},true),[]);
const badLabels = '<!-- bilingual:section -->\n<!-- lang:zh -->\n\n<strong>EN:</strong> 中文段落。\n\n- **ZH:** 中文列表项\n\n## 不应在栏内\n\n<!-- lang:en -->\n\nEN: English paragraph.\n\n### Heading in language column\n\n```md\nEN: example label\n```\n\n<!-- /bilingual:section -->';
const badLabelErrors = check(header + badLabels, {bilingual_format:'magazine-v1'}, true);
assert(badLabelErrors.some(error => error.includes('中文语言栏内不得残留 EN:/ZH: 标签')));
assert(badLabelErrors.some(error => error.includes('英文语言栏内不得残留 EN:/ZH: 标签')));
assert.equal(badLabelErrors.filter(error => error.includes('语言栏内不得包含标题')).length, 2);
const directQuote = '<!-- bilingual:section -->\n<!-- lang:zh -->\n\n这是普通中文。\n\n<!-- lang:en -->\n\n“EN: is part of this quoted sentence.”\n\n<!-- /bilingual:section -->';
assert.deepEqual(check(header + directQuote, {bilingual_format:'magazine-v1'}, true), []);
const codeExample = section.replace('Complete English prose.', 'Complete English prose mentioning EN: without a prefix.\n\n```md\nEN: example label\n# Example heading\n```');
assert.deepEqual(check(header + codeExample, {bilingual_format:'magazine-v1'}, true), []);
assert(check(header+section.replace('<!-- lang:en -->',''),{bilingual_format:'magazine-v1'}).length);
assert(check(header+body,{tags:['双语翻译']},true).length);
assert.deepEqual(check(header+body,{tags:['双语翻译']},false),[]); // Grandfather existing prose.
assert.equal(render('# 中文文章\n\n---\n\n普通中文。\n\nAn English citation.\n\n中文说明。',marked).sections.length,0);
assert.equal(render(header+'```html\n<!-- bilingual:section -->\n```',marked).sections.length,0);
assert.equal(render(header+'> Genuine source quote.\n\n真正引语的说明。',marked).sections.length,0);
console.log('PASS: editorial grouping, one-to-many translations, list/link semantics, media/code boundaries, genuine quotes, canonical contract, legacy compatibility');
